name: Onigokko
version: '1.0.0'
main: com.github.onigokko.Onigokko
api-version: '1.20'
authors: [ 25tomo ]
description: spigot鬼ごプラグイン

commands:
  setgametime:
    description: ゲーム時間設定コマンド/set gametime command
    usage: /setgametime [time]
  setgamemode:
    description: ゲームモード設定コマンド/set gamemode command
    usage: /setgametime [mode]