name: Onigokko
version: '1.0.0'
main: com.github.onigokko.Onigokko
api-version: '1.20'
authors: [ 25tomo ]
description: spigot鬼ごプラグイン

commands:
  setgametime:
    description: ゲーム時間設定コマンド/set game time command
    usage: /setgametime [time]
  setgamemode:
    description: ゲームモード設定コマンド/set game mode command
    usage: /setgametime [mode]
  startgame:
    description: ゲーム開始コマンド/ start game command
    usage: /startgame
  stopgame:
    description: ゲーム停止コマンド/ stop game command
    usage: /stopgame
  setteam:
    description: プレイヤーをチームに追加するコマンド
    usage: /setteam <oni | nige> <player | random> <int>
  setstart:
    description: スタート地点設定コマンド
    usage: /setstart